### ISSUE TITLE
Error while pressing signin or sign up

### ISSUE THREAD

**Issue by woinbo** [itsmaheshkariya/flutter-node-mongodb-login-registration#2]
Hello sir, 
Sir this is a very awesome tutorial, but sir I'm getting an error while signing in or signing up, 
the error is 
```E/flutter ( 4956): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 55530```
sir each time I press the sign in or signup button it changes the port(in this error it is 55530) value, but my API is hosted locally i.e., 127.0.0.1:3000,
![flutter error](https://user-images.githubusercontent.com/62764278/95119906-58a3f500-076a-11eb-804c-c607785571e6.PNG)

sir, please provide a soln to this problem

**Comment by itsmaheshkariya** [comment]
it sound silly but you can update android studio and after that you just
need to cross check your
flutter doctor
and try to Change localhost to IPV4 address if possible.

**Comment by woinbo** [comment]
Thank you for your solution, but I changed the URL from "http://127.0.0.1:8080/signup" to "http://10.0.2.2:8080/signup",
and it worked perfectly.
Well, thanks for your reply.
